import { useEffect, useState } from 'react'
import { api } from '../api'
import { useShop } from '../context/ShopContext'
import { formatPrice } from '../data/catalog'
import { Tab } from '../components/common/Tabs'

export default function AdminPage() {
    const { user, setToast } = useShop()
    const [tab, setTab] = useState('dashboard')
    const [dashboard, setDashboard] = useState(null)
    const [orders, setOrders] = useState([])
    const [product, setProduct] = useState({ name: '', description: '', price: '', discountPrice: '', stockQuantity: '', sku: '', brand: '', categoryId: '', imageUrl: '', active: true })
    const isSuperAdmin = user?.role === 'SUPER_ADMIN'
    const load = () => { api('/api/admin/dashboard').then(setDashboard).catch(error => setToast(error.message)); api('/api/admin/orders?size=30').then(page => setOrders(page.content || [])).catch(error => setToast(error.message)) }
    useEffect(() => { load() }, [])
    const updateStatus = async (id, status) => { try { await api(`/api/admin/orders/${id}/status?status=${status}`, { method: 'PUT' }); load(); setToast('Order status updated.') } catch (error) { setToast(error.message) } }
    const createProduct = async event => { event.preventDefault(); try { await api('/api/products', { method: 'POST', body: JSON.stringify({ ...product, price: Number(product.price), stockQuantity: Number(product.stockQuantity), categoryId: Number(product.categoryId), discountPrice: product.discountPrice ? Number(product.discountPrice) : null }) }); setToast('Product created successfully.'); setProduct({ name: '', description: '', price: '', discountPrice: '', stockQuantity: '', sku: '', brand: '', categoryId: '', imageUrl: '', active: true }) } catch (error) { setToast(error.message) } }
    const fields = [['name', 'Product name'], ['sku', 'SKU'], ['brand', 'Brand'], ['categoryId', 'Category ID'], ['price', 'Price'], ['discountPrice', 'Discount price'], ['stockQuantity', 'Stock quantity'], ['imageUrl', 'Image URL']]
    return <section className="mx-auto max-w-7xl px-5 py-12 lg:px-12"><p className="text-xs font-bold uppercase tracking-widest text-[#a96f36]">{isSuperAdmin ? 'Super admin' : 'Admin'} workspace</p><h1 className="mt-2 font-serif text-4xl">Store management</h1><div className="mt-9 flex gap-6 border-b border-slate-200"><Tab active={tab === 'dashboard'} onClick={() => setTab('dashboard')}>Dashboard</Tab><Tab active={tab === 'orders'} onClick={() => setTab('orders')}>Orders</Tab><Tab active={tab === 'products'} onClick={() => setTab('products')}>Add product</Tab></div>{tab === 'dashboard' && <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(dashboard || {}).map(([key, value]) => <article key={key} className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{key.replace(/([A-Z])/g, ' $1')}</p><p className="mt-3 font-serif text-3xl">{typeof value === 'number' ? value.toLocaleString('en-IN') : String(value)}</p></article>)}</div>}{tab === 'orders' && <div className="mt-7 overflow-x-auto rounded-2xl bg-white ring-1 ring-slate-200"><table className="min-w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Order</th><th className="p-4">Status</th><th className="p-4">Amount</th><th className="p-4">Update</th></tr></thead><tbody>{orders.map(order => <tr key={order.id} className="border-b last:border-0"><td className="p-4 font-medium">{order.orderNumber}</td><td className="p-4">{order.orderStatus}</td><td className="p-4">{formatPrice(order.totalAmount)}</td><td className="p-4"><select value={order.orderStatus} onChange={event => updateStatus(order.id, event.target.value)} className="rounded border px-2 py-1 text-xs"><option>PLACED</option><option>CONFIRMED</option><option>SHIPPED</option><option>DELIVERED</option><option>CANCELLED</option></select></td></tr>)}</tbody></table></div>}{tab === 'products' && <form onSubmit={createProduct} className="mt-7 max-w-3xl rounded-2xl bg-white p-6 ring-1 ring-slate-200"><h2 className="font-serif text-2xl">Add a product</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{fields.map(([key, label]) => <input key={key} required={!key.includes('discount')} type={['price', 'discountPrice', 'stockQuantity', 'categoryId'].includes(key) ? 'number' : 'text'} value={product[key]} onChange={event => setProduct({ ...product, [key]: event.target.value })} placeholder={label} className="rounded-lg border px-3 py-2.5 text-sm" />)}<textarea required value={product.description} onChange={event => setProduct({ ...product, description: event.target.value })} placeholder="Description" className="min-h-28 rounded-lg border px-3 py-2.5 text-sm sm:col-span-2" /></div><button className="mt-5 rounded-lg bg-[#101726] px-6 py-3 text-sm font-bold text-white">Create product</button></form>}</section>
}